spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/zhaopin?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  resources:
    static-locations: classpath:/webapp/templates/
  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/webapp/templates/
    suffix: .ftl


mybatis:
  mapper-locations: classpath:/mapper/*.xml
management:
  ssl:
    key-store: classpath:/keystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
    protocol: TLS
    key-password: 123456
    key-store-password: 123456
    client-auth: want

server:
  port: 443
  max-http-header-size: 10000
  connection-timeout: 20000
  tomcat:
    max-threads: 150
